baseURL: ""
languageCode: en-us
title: "Samson not Ajadalu"
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enhanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Samson Ajadalu"
    subtitle: "Hi 👋 I’m Samsonn to make a real impact.!"
    imageUrl: "home/casual-small-square.jpeg"
    imageWidth: 220
    imageHeight: 220

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:abdur.rahman.kalim@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/abdurrahmankalim"
    - name: "github"
      url: "https://github.com/arkalim"
    - name: "youtube"
      url: "https://www.youtube.com/c/AbdurRahmanKalim"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
